# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/uom-project',
                'doc_host': 'https://AugustasMacijauskas.github.io',
                'git_url': 'https://github.com/AugustasMacijauskas/uom-project',
                'lib_path': 'uom_project'},
  'syms': { 'uom_project.poisson_solvers': { 'uom_project.poisson_solvers.poisson_gauss_seidel_solver': ( 'poisson_solvers.html#poisson_gauss_seidel_solver',
                                                                                                          'uom_project/poisson_solvers.py')}}}
