# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/uom-project',
                'doc_host': 'https://AugustasMacijauskas.github.io',
                'git_url': 'https://github.com/AugustasMacijauskas/uom-project',
                'lib_path': 'uom_project'},
  'syms': {'uom_project.core': {'uom_project.core.foo': ('core.html#foo', 'uom_project/core.py')}}}
